id = "Yapper"
name = "Yapper"
description = "TTS Accessibility Utility for WEBFISHING."
version = "0.0.1"
homepage = "https://github.com/WFMacroplastics/WebfishingYapper"
author = "Sulayre, Awesomerly"

icon = "icon.png"
readme = "README.md"

extra_files = [ "libgdtts.windows.x86_64.dll", "LICENSE" ]

[project]
godot = "./project/project.godot"
csharp = "./Yapper/Yapper.csproj"

[[dependencies]]
thunderstore_version = "NotNet-GDWeave-2.0.13"

[[dependencies]]
id = "BlueberryWolfi.APIs"
thunderstore_version = "BlueberryWolfi-BlueberryWolfiAPIs-1.0.2"

[[dependencies]]
id = "LucysLib"
thunderstore_version = "team_sea_slug-LucysLib-0.1.1"